ign -> gz Partial Docs Migration and Project Name Followups : gz-gui
gazebosim/gz-gui pull request #425
Opened 2022-06-28 00:00 UTC by methylDragon

See: https://github.com/gazebo-tooling/release-tools/issues/757

2022-06-28 17:21 UTC, chapulina requested changes

2022-06-28 18:56 UTC, methylDragon commented on doc/qt.tag.xml
> +            <anchor>assgz-2</anchor>
Rectified!

2022-06-28 19:57 UTC, jennuine reviewed
Found some other docs that may need updating

2022-06-28 19:57 UTC, jennuine commented on src/plugins/scene3d/Scene3D.hh
>    /// All ign-rendering calls should be performed inside this class as it makes
```suggestion
  /// All gz-rendering calls should be performed inside this class as it makes
```

2022-06-29 01:26 UTC, chapulina approved these changes

2022-06-29 01:26 UTC, merged