Add common widget for vector3
gazebosim/gz-gui pull request #427
Opened 2022-06-28 20:58 UTC by AzulRadio

Signed-off-by: youhy <haoyuan2019@outlook.com>

# New feature

## Summary
Add common widget for vector3

## Test it
Use the following test QML to test: 
```
import QtQuick 2.9
import QtQuick.Layouts 1.3

GzVector3 {
  id: gzVector
  property double xModel: 120
  property double yModel: 110
  property double zModel: 100
  xName: "Red"
  yName: "Green"
  zName: "Blue"
  xSpin.value: xModel
  ySpin.value: yModel
  zSpin.value: zModel
  onGzVectorSet: {
    xModel = xSpin.value
    yModel = ySpin.value
    zModel = zSpin.value
    console.log(xModel, yModel, zModel)
  }
}
```
Then use
```
qmlscene Test.qml
```
to test
## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-07-08 18:41 UTC, chapulina requested changes

2022-07-08 18:41 UTC, chapulina commented on include/ignition/gui/qml/GzVector3.qml
> +  property double spinMax: 1000000
```suggestion
  property double spinMax: Number.MAX_VALUE
```

2022-07-08 18:41 UTC, chapulina commented on include/ignition/gui/qml/GzVector3.qml
> +  property bool show: true
Let's make it consistent with pose, call it expand and make it public

2022-07-08 18:41 UTC, chapulina commented on include/ignition/gui/qml/GzVector3.qml
> +  property int margin: 5
Let's move the marging and indentation logic to the parent of this widget

2022-07-08 18:41 UTC, chapulina commented on include/ignition/gui/qml/GzVector3.qml
> +  IgnHelpers {
You could use the one from `IgnHelpers.qml` here

2022-07-08 18:41 UTC, chapulina commented on include/ignition/gui/qml/GzVector3.qml
> +Rectangle {
The widget's background color is plain white, but it should follow the parent's color.

Before this PR:

![image](https://user-images.githubusercontent.com/5751272/178051615-47d2ad8f-3cf8-424e-8b10-b5f1bf23f24f.png)


With this PR:

![image](https://user-images.githubusercontent.com/5751272/178051496-1e8f7bf1-28c2-4467-8287-4e1df439fa9e.png)

2022-07-11 17:25 UTC, jennuine approved these changes

2022-07-11 17:25 UTC, jennuine commented on include/ignition/gui/qml/GzVector3.qml
> +  // Set to "" to omit the parentheses.
```suggestion
  // Set to "" to omit the units & parentheses.
```

2022-07-11 17:25 UTC, jennuine commented on include/ignition/gui/qml/GzVector3.qml
> +  property double spinMax: Number.MAX_VALUE
This should be moved out of the private variables section since users can overwrite

2022-07-13 21:15 UTC, merged