Fixed topic echo test
gazebosim/gz-gui pull request #448
Opened 2022-07-30 00:23 UTC by jennuine

# 🦟 Bug fix

Part of https://github.com/gazebosim/gz-sim/issues/1575

## Summary
Fixed the `TopicEcho_TEST`.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- ~~[ ] Updated documentation (as needed)~~
- ~~[ ] Updated migration guide (as needed)~~
- ~~[ ] Consider updating Python bindings (if the library has them)~~
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-07-30 00:27 UTC, chapulina approved these changes
Nice! LGTM if it passes CI.

2022-07-30 10:15 UTC, ahcorde requested changes

2022-07-30 10:15 UTC, ahcorde commented on src/plugins/topic_echo/TopicEcho_TEST.cc
> +  app.AddPluginPath(std::string(PROJECT_BINARY_PATH) + "/lib");
common::joinPaths

2022-07-30 10:15 UTC, ahcorde commented on src/plugins/topic_echo/TopicEcho_TEST.cc
> +  app.AddPluginPath(std::string(PROJECT_BINARY_PATH) + "/lib");
common::JoinPaths

2022-08-01 17:06 UTC, jennuine commented on src/plugins/topic_echo/TopicEcho_TEST.cc
> +  app.AddPluginPath(std::string(PROJECT_BINARY_PATH) + "/lib");
118d4d5943ecf97a498ae4facd9a7091fb6e417b

2022-08-01 17:06 UTC, jennuine commented on src/plugins/topic_echo/TopicEcho_TEST.cc
> +  app.AddPluginPath(std::string(PROJECT_BINARY_PATH) + "/lib");
118d4d5943ecf97a498ae4facd9a7091fb6e417b

2022-08-02 16:04 UTC, chapulina approved these changes
Thanks for bringing that test back!

2022-08-02 16:05 UTC, merged